name: Build

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET 8
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 8.0.x
            - name: Setup .NET 9
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 9.0.x
            - name: Clean build
              run: dotnet clean
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            - name: Test
              run: dotnet test --no-build --verbosity normal